import { TPromptList } from "@/@types/prompt";

const prompts: TPromptList = [
  { name: "ログイン端末名", value: "%l", preview: "s003" },
  { name: "ログイン端末名(tty省略)", value: "%y", preview: "ttys003" },
  { name: "マシン名", value: "%M", preview: "MacBook-Pro.elecom" },
  { name: "マシン名( . まで)", value: "%m", preview: "MacBook-Pro" },
  { name: "ユーザ名", value: "%n", preview: "ryota-k" },
  { name: "root : #,  それ以外 : %", value: "%#", preview: "%" },
  {
    name: "直前のコマンドの戻り値 (成功 : 0,  command not found : 127 …)",
    value: "%?",
    preview: "0",
  },
  {
    name: "カレントディレクトリまでのpath",
    value: "%d",
    preview: "/Users/ryota-k/dev",
  },
  {
    name: "カレントディレクトリまでのpath ( $HOME → ~)",
    value: "%~",
    preview: "~/dev",
  },
  { name: "historyのインデックス", value: "%h", preview: "1035" },
  { name: "現在のindex(開き直すとreset)", value: "%i", preview: "12" },
  { name: "ジョブの数", value: "%j", preview: "0" },
  { name: "シェルの深さ", value: "%L", preview: "1" },
  { name: "shell", value: "%N", preview: "/bin/zsh" },
  { name: "カレントディレクトリ", value: "%c", preview: "dev" },
  { name: "日付(yy-mm-dd)", value: "%D", preview: "22-12-06" },
  { name: "日付(曜-dd形式)", value: "%w", preview: "火  6" },
  { name: "時刻(24h形式)", value: "%T", preview: "17:20" },
  { name: "時刻(24h形式 + 秒)", value: "%*", preview: "17:20:35" },
  { name: "時刻(12h形式)", value: "%T", preview: "5:20PM" },
  { name: "太字(始)", value: "%B", preview: "" },
  { name: "太字(終)", value: "%b", preview: "" },
  { name: "下線(始)", value: "%U", preview: "" },
  { name: "下線(終)", value: "%u", preview: "" },
  { name: "スタンドアウト(始)", value: "%S", preview: "" },
  { name: "スタンドアウト(終)", value: "%s", preview: "" },
  { name: "文字色(黒)", value: "%F{0}", preview: "" },
  { name: "文字色(赤)", value: "%F{1}", preview: "" },
  { name: "文字色(緑)", value: "%F{2}", preview: "" },
  { name: "文字色(黄)", value: "%F{3}", preview: "" },
  { name: "文字色(青)", value: "%F{4}", preview: "" },
  { name: "文字色(紫)", value: "%F{5}", preview: "" },
  { name: "文字色(水)", value: "%F{6}", preview: "" },
  { name: "文字色(白)", value: "%F{7}", preview: "" },
  { name: "文字色(終)", value: "%f", preview: "" },
  { name: "背景色(黒)", value: "%K{0}", preview: "" },
  { name: "背景色(赤)", value: "%K{1}", preview: "" },
  { name: "背景色(緑)", value: "%K{2}", preview: "" },
  { name: "背景色(黄)", value: "%K{3}", preview: "" },
  { name: "背景色(青)", value: "%K{4}", preview: "" },
  { name: "背景色(紫)", value: "%K{5}", preview: "" },
  { name: "背景色(水)", value: "%K{6}", preview: "" },
  { name: "背景色(白)", value: "%K{7}", preview: "" },
  { name: "背景色(終)", value: "%k", preview: "" },
];

export { prompts };
